POST  http://localhost:3003/products
Content-Type: application/json

    {
     "name": "VESTIDO CURTO VELUDO RECORTE GOLA",
    "tags": ["colorido", "viagem", "delicado", "descolado", "inverno"]
    }
###
GET http://localhost:3003/products/chevron


